name: Version

on:
  workflow_run:
    branches: [main]
    workflows: [Test]
    types: [completed]

  push:
    branches:
      - main

jobs:
  version:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    env:
      PYTHONPATH: "."

    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Install Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.14"

      - name: Install UV
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9

      - name: Install dependencies
        run: uv sync

      - name: Configure git
        run: |
          git remote set-url origin "https://x-access-token:${{ secrets.GH_ACCESS_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git/"

          git config user.name "Malik Mahmud"
          git config user.email "almalikmahmud@gmail.com"

      - name: Bump version and create git tag
        run: |
          uv run scripts/version.py
          git push && git push --tags
