name: Version and Release

on:
  workflow_run:
    branches: [main]
    workflows: [Test]
    types: [completed]

permissions:
  contents: write

jobs:
  version:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    env:
      PYTHONPATH: "."

    outputs:
      tag_name: ${{ steps.bump_version.outputs.tag_name }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.14"

      - name: Install UV
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9

      - name: Install dependencies
        run: uv sync

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Bump version and create git tag
        id: bump_version
        run: |
          uv run scripts/version.py
          git push && git push --tags
          echo "tag_name=$(git describe --tags --abbrev=0 | tr -d '\n')" >> "$GITHUB_OUTPUT"

  release:
    needs: version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Release latest version
        env:
          TAG_NAME: ${{ needs.version.outputs.tag_name }}
          GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: gh release create "${TAG_NAME}" --fail-on-no-commits --generate-notes
